=== consulo/consulo-css/consulo-xstylesheet/rsc/org/consulo/xstylesheet/defaultXStyleSheetTable.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="xstyle-sheet-table" type="xstyle-sheet-tableType"/>
  <xs:complexType name="propertyType" mixed="true">
    <xs:sequence>
      <xs:element type="valid-valuesType" name="valid-values"/>
      <xs:element type="initial-valuesType" name="initial-values" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
  </xs:complexType>
  <xs:complexType name="value-definitionType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="implClass" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="entryType">
    <xs:sequence>
      <xs:element type="xs:string" name="color" minOccurs="0"/>
      <xs:element type="xs:string" name="colorKeyword" minOccurs="0"/>
      <xs:element type="xs:string" name="keyword" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element name="percentNumber" maxOccurs="unbounded" minOccurs="0" />
      <xs:element name="relativeLengthNumber" maxOccurs="unbounded" minOccurs="0" />
      <xs:element name="absoluteLengthNumber" maxOccurs="unbounded" minOccurs="0" />
      <xs:element name="number" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="initial-valuesType">
    <xs:sequence>
      <xs:element type="entryType" name="entry"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="xstyle-sheet-tableType">
    <xs:sequence>
      <xs:element type="value-definitionType" name="value-definition" maxOccurs="unbounded" minOccurs="0">
        <xs:annotation>
          <xs:documentation>http://www.w3.org/TR/CSS21/propidx.html</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="propertyType" name="property" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="valid-valuesType">
    <xs:sequence>
      <xs:element type="entryType" name="entry"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== consulo/consulo-css/consulo-xstylesheet/resources/org/consulo/xstylesheet/defaultXStyleSheetTable.xml
<?xml version="1.0" encoding="UTF-8"?>
<xstyle-sheet-table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:noNamespaceSchemaLocation="defaultXStyleSheetTable.xsd">
	<!--http://www.w3.org/TR/CSS21/propidx.html-->
	<value-definition name="color" implClass="org.consulo.xstylesheet.definition.value.impl.ColorXStyleSheetValue"/>
	<value-definition name="colorKeyword" implClass="org.consulo.xstylesheet.definition.value.impl.KeywordColorXStyleSheetValue"/>
	<value-definition name="keyword" implClass="org.consulo.xstylesheet.definition.value.impl.KeywordXStyleSheetValue"/>
	<value-definition name="number" implClass="org.consulo.xstylesheet.definition.value.impl.NumberXStyleSheetValue"/>
	<value-definition name="percentNumber" implClass="org.consulo.xstylesheet.definition.value.impl.PercentNumberXStyleSheetValue"/>
	<value-definition name="relativeLengthNumber" implClass="org.consulo.xstylesheet.definition.value.impl.RelativeLengthNumberXStyleSheetValue"/>
	<value-definition name="absoluteLengthNumber" implClass="org.consulo.xstylesheet.definition.value.impl.AbsoluteLengthNumberXStyleSheetValue"/>
	<value-definition name="function" implClass="org.consulo.xstylesheet.definition.value.impl.FunctionXStyleSheetValue"/>

	<property name="background-color">
		<valid-values>
			<entry>
				<color/>
				<colorKeyword/>
				<keyword>transparent</keyword>
				<keyword>inherit</keyword>
			</entry>
		</valid-values>
		<initial-values>
			<entry>
				<keyword>transparent</keyword>
			</entry>
		</initial-values>
	</property>
	<property name="color">
		<valid-values>
			<entry>
				<color/>
				<colorKeyword/>
				<keyword>inherit</keyword>
			</entry>
		</valid-values>
		<initial-values>
			<entry>
				<keyword>inherit</keyword>
			</entry>
		</initial-values>
	</property>
	<property name="background-image">
		<valid-values>
			<entry>
				<function />
				<keyword>inherit</keyword>
				<keyword>none</keyword>
			</entry>
		</valid-values>
		<initial-values>
			<entry>
				<keyword>inherit</keyword>
			</entry>
		</initial-values>
	</property>
	<property name="background-repeat">
		<valid-values>
			<entry>
				<keyword>repeat</keyword>
				<keyword>repeat-x</keyword>
				<keyword>repeat-y</keyword>
				<keyword>no-repeat</keyword>
				<keyword>inherit</keyword>
			</entry>
		</valid-values>
		<initial-values>
			<entry>
				<keyword>repeat</keyword>
			</entry>
		</initial-values>
	</property>
	<property name="visibility">
		<valid-values>
			<entry>
				<keyword>visible</keyword>
				<keyword>hidden</keyword>
				<keyword>collapse</keyword>
				<keyword>inherit</keyword>
			</entry>
		</valid-values>
		<initial-values>
			<entry>
				<keyword>visible</keyword>
			</entry>
		</initial-values>
	</property>
	<property name="font-weight">
		<valid-values>
			<entry>
				<keyword>normal</keyword>
				<keyword>bold</keyword>
				<keyword>bolder</keyword>
				<keyword>lighter</keyword>
				<keyword>inherit</keyword>
				<number>100</number>
				<number>200</number>
				<number>300</number>
				<number>400</number>
				<number>500</number>
				<number>600</number>
				<number>700</number>
				<number>800</number>
				<number>900</number>
			</entry>
		</valid-values>
		<initial-values>
			<entry>
				<keyword>normal</keyword>
			</entry>
		</initial-values>
	</property>
	<property name="font-style">
		<valid-values>
			<entry>
				<keyword>normal</keyword>
				<keyword>italic</keyword>
				<keyword>oblique</keyword>
				<keyword>inherit</keyword>
			</entry>
		</valid-values>
		<initial-values>
			<entry>
				<keyword>normal</keyword>
			</entry>
		</initial-values>
	</property>
	<property name="font-variant">
		<valid-values>
			<entry>
				<keyword>normal</keyword>
				<keyword>small-caps</keyword>
				<keyword>inherit</keyword>
			</entry>
		</valid-values>
		<initial-values>
			<entry>
				<keyword>normal</keyword>
			</entry>
		</initial-values>
	</property>
	<property name="float">
		<valid-values>
			<entry>
				<keyword>left</keyword>
				<keyword>right</keyword>
				<keyword>none</keyword>
				<keyword>inherit</keyword>
			</entry>
		</valid-values>
		<initial-values>
			<entry>
				<keyword>none</keyword>
			</entry>
		</initial-values>
	</property>
	<property name="empty-cells">
		<valid-values>
			<entry>
				<keyword>show</keyword>
				<keyword>hide</keyword>
				<keyword>inherit</keyword>
			</entry>
		</valid-values>
		<initial-values>
			<entry>
				<keyword>show</keyword>
			</entry>
		</initial-values>
	</property>
	<property name="background-attachment">
		<valid-values>
			<entry>
				<keyword>scroll</keyword>
				<keyword>fixed</keyword>
				<keyword>inherit</keyword>
			</entry>
		</valid-values>
		<initial-values>
			<entry>
				<keyword>scroll</keyword>
			</entry>
		</initial-values>
	</property>
	<property name="border-collapse">
		collapse | separate | inherit
		<valid-values>
			<entry>
				<keyword>collapse</keyword>
				<keyword>separate</keyword>
				<keyword>inherit</keyword>
			</entry>
		</valid-values>
		<initial-values>
			<entry>
				<keyword>separate</keyword>
			</entry>
		</initial-values>
	</property>
	<property name="border-top-color">
		<valid-values>
			<entry>
				<color/>
				<colorKeyword/>
				<keyword>transparent</keyword>
				<keyword>inherit</keyword>
			</entry>
		</valid-values>
	</property>
	<property name="border-right-color">
		<valid-values>
			<entry>
				<color/>
				<colorKeyword/>
				<keyword>transparent</keyword>
				<keyword>inherit</keyword>
			</entry>
		</valid-values>
	</property>
	<property name="border-bottom-color">
		<valid-values>
			<entry>
				<color/>
				<colorKeyword/>
				<keyword>transparent</keyword>
				<keyword>inherit</keyword>
			</entry>
		</valid-values>
	</property>
	<property name="border-left-color">
		<valid-values>
			<entry>
				<color/>
				<colorKeyword/>
				<keyword>transparent</keyword>
				<keyword>inherit</keyword>
			</entry>
		</valid-values>
	</property>
</xstyle-sheet-table>
